set(_CATKIN_CURRENT_PACKAGE "live_demo")
set(live_demo_VERSION "0.0.0")
set(live_demo_MAINTAINER "dhriti <dhriti@todo.todo>")
set(live_demo_PACKAGE_FORMAT "2")
set(live_demo_BUILD_DEPENDS )
set(live_demo_BUILD_EXPORT_DEPENDS )
set(live_demo_BUILDTOOL_DEPENDS "catkin")
set(live_demo_BUILDTOOL_EXPORT_DEPENDS )
set(live_demo_EXEC_DEPENDS )
set(live_demo_RUN_DEPENDS )
set(live_demo_TEST_DEPENDS )
set(live_demo_DOC_DEPENDS )
set(live_demo_URL_WEBSITE "")
set(live_demo_URL_BUGTRACKER "")
set(live_demo_URL_REPOSITORY "")
set(live_demo_DEPRECATED "")