set(_CATKIN_CURRENT_PACKAGE "arena_with_qr")
set(arena_with_qr_VERSION "0.0.0")
set(arena_with_qr_MAINTAINER "sra <sra@todo.todo>")
set(arena_with_qr_PACKAGE_FORMAT "2")
set(arena_with_qr_BUILD_DEPENDS )
set(arena_with_qr_BUILD_EXPORT_DEPENDS )
set(arena_with_qr_BUILDTOOL_DEPENDS "catkin")
set(arena_with_qr_BUILDTOOL_EXPORT_DEPENDS )
set(arena_with_qr_EXEC_DEPENDS )
set(arena_with_qr_RUN_DEPENDS )
set(arena_with_qr_TEST_DEPENDS )
set(arena_with_qr_DOC_DEPENDS )
set(arena_with_qr_URL_WEBSITE "")
set(arena_with_qr_URL_BUGTRACKER "")
set(arena_with_qr_URL_REPOSITORY "")
set(arena_with_qr_DEPRECATED "")